language: php
php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - vendor/bin/phpunit

notifications:
  email:
    - james.t.halsall@googlemail.com

